[project]
name = "iss-tracker"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "matplotlib>=3.10.3",
    "rasterio>=1.4.3",
    "skyfield>=1.53",
]
